name: Cabal CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['9.12.4', '9.14.1']
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 'latest'
      - run: cabal update
      - run: cabal build all
      - run: cabal test all --test-show-details=streaming
